spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/boardp
    username: jal
    password: jal1234
#  devtools:
#    restart:
#      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true # html th:method="put" 작동
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true # sql문을 보기 좋게 출력함
    show-sql: true
  thymeleaf:
    cache: false
