spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/boardp
    username: jal
    password: jal1234

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
  thymeleaf:
    cache: false
